# Variables to be set in .env
version: '3.0'

services:
  novemdoc-mongo:
    image: mongo
    restart: always
    ports:
        - ${MONGO_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  trunk-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${ME_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: novemdoc-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_PASSWORD}
